=== PedroIsaac09/pos-2025-tarefas/xml/definicoes.dtd
<!ELEMENT cardapio (Prato+)>
<!ELEMENT Prato (nomedoprato, descricao, Ingredientes+, Preco, Calorias*, Tempo_de_preparo)>
<!ATTLIST Prato id ID #REQUIRED>
<!ELEMENT nomedoprato (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT Ingredientes (Ingrediente+)>
<!ELEMENT Ingrediente (#PCDATA)>
<!ELEMENT Preco (#PCDATA)>
<!ATTLIST Preco moeda (BRL | USD) "BRL">
<!ELEMENT Calorias (#PCDATA)>
<!ELEMENT Tempo_de_preparo (#PCDATA)>
<!ENTITY  reais "R$">

=== PedroIsaac09/pos-2025-tarefas/xml/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">

<cardapio>
    <Prato id="L01">
        <nomedoprato>Carne ao molho</nomedoprato>
        <descricao>Carne com molho francês</descricao>
        <Ingredientes>
            <Ingrediente>Carne assada</Ingrediente>
            <Ingrediente>Molho comprado no mercado</Ingrediente>
        </Ingredientes>
        <Preco moeda="BRL">&reais; 220R$</Preco>
        <Calorias>25000 kcal</Calorias>
        <Tempo_de_preparo>2h de preparo</Tempo_de_preparo>
    </Prato>
    <Prato id="L02">
        <nomedoprato>Frango frito</nomedoprato>
        <descricao>Frango frito gostoso para almoço</descricao>
        <Ingredientes>
            <Ingrediente>Frango</Ingrediente>
            <Ingrediente>Óleo para fritar</Ingrediente>
        </Ingredientes>
        <Preco moeda="BRL">&reais; 60R$</Preco>
        <Calorias>200 kcal</Calorias>
        <Tempo_de_preparo>1h de preparo</Tempo_de_preparo>
    </Prato>
    <Prato id="L03">
        <nomedoprato>Feijão e arroz</nomedoprato>
        <descricao>Feijão com arroz</descricao>
        <Ingredientes>
            <Ingrediente>Feijão</Ingrediente>
            <Ingrediente>Arroz</Ingrediente>
        </Ingredientes>
        <Preco moeda="BRL">&reais; 25R$</Preco>
        <Calorias>1500 kcal</Calorias>
        <Tempo_de_preparo>2h de preparo</Tempo_de_preparo>
    </Prato>
    <Prato id="L04">
        <nomedoprato>Peixe</nomedoprato>
        <descricao>Peixe assado</descricao>
        <Ingredientes>
            <Ingrediente>Peixe</Ingrediente>
            <Ingrediente>Ervas finas</Ingrediente>
        </Ingredientes>
        <Preco moeda="BRL">&reais; 20R$</Preco>
        <Calorias>230 kcal</Calorias>
        <Tempo_de_preparo>30 minutos de preparo</Tempo_de_preparo>
    </Prato>
    <Prato id="L05">
        <nomedoprato>Frango na grelha</nomedoprato>
        <descricao>Frango na grelha</descricao>
        <Ingredientes>
            <Ingrediente>Frango</Ingrediente>
            <Ingrediente>Temperos</Ingrediente>
        </Ingredientes>
        <Preco moeda="BRL">&reais; 25R$</Preco>
        <Calorias>450 kcal</Calorias>
        <Tempo_de_preparo>1h de preparo</Tempo_de_preparo>
    </Prato>
</cardapio>
